# Generated by Django 4.2.16 on 2024-11-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fencer",
            name="discipline",
            field=models.PositiveIntegerField(
                choices=[(1, "Epee"), (2, "Sabre"), (3, "Fleuret")], default=1
            ),
        ),
        migrations.AddField(
            model_name="referee",
            name="nb_tournaments_officiated",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="nb_tournaments_participated",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="nb_tournaments_won",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="ranking",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="referee",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
