# Generated by Django 4.2.16 on 2024-11-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_competitor_nb_tournaments_won_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fencer",
            name="club",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
