# Generated by Django 4.2.16 on 2024-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_fencer_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="ranking",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
