# Generated by Django 4.2.16 on 2024-11-02 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_fencer_discipline_referee_nb_tournaments_officiated_and_more"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="competitor_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_competitor1",
                to="users.competitor",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="competitor_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_competitor2",
                to="users.competitor",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.pool",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="score",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Pool"),
                    (1, "Round of 32"),
                    (2, "Round of 16"),
                    (3, "Round of 8"),
                    (4, "Round of 4"),
                    (5, "Final"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="max_competitors",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="pool",
            name="tournament_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
