# Generated by Django 4.2.16 on 2024-11-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_competitor_profil_pic_competitor_tournament_and_more"),
        (
            "tournaments",
            "0002_match_competitor_1_match_competitor_2_match_pool_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="ongoing",
        ),
        migrations.AddField(
            model_name="tournament",
            name="state",
            field=models.CharField(
                choices=[
                    ("FUN", "Fun"),
                    ("REG", "Registration"),
                    ("STA", "Started"),
                    ("END", "Finished"),
                ],
                default="FUN",
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("tournament", "competitor_1", "competitor_2")},
        ),
    ]
