# Generated by Django 4.2.16 on 2024-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_tournament_use_pools_alter_tournament_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
