# Generated by Django 4.2.16 on 2024-11-02 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_fencer_club"),
        ("tournaments", "0005_tournament_winner"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="users.competitor",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitors",
                        to="tournaments.pool",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("tournament", "competitor")},
            },
        ),
    ]
