# Generated by Django 4.2.16 on 2024-11-03 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tournaments",
            "0006_alter_match_unique_together_alter_tournament_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="nb_participants",
            new_name="max_nb_participants",
        ),
    ]
